[package]
name = "avored-rust-cms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.20", features = ["multipart"] }
handlebars = { version = "4.4.0", features = ["dir_source"] }
serde = { version = "1.0.188", features = ["derive"] }
tokio = { version = "1.32.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
r_i18n = "1.0.1"
tower-http = { version = "0.4.3", features = ["fs"] }
dotenvy = "0.15.7"
async-session = "3.0.0"
axum-extra = { version = "0.7.7", features = ["cookie", "cookie-signed"] }
futures = "0.3.28"
tower = "0.4.13"
surrealdb = { version = "1.0.0-beta.12", features = ["kv-rocksdb"] }
argon2 = "0.5.2"
avored_better_query = { path = "./avored_better_query" }
validator = { version = "0.16.1", features = ["derive"] }
rand = "0.8.5"
urlencoding = "2.1.3"
