[package]
name = "avored-rust-cms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-session = "3.0.0"
axum = "0.6.20"
axum-extra = { version = "0.7.7", features = ["cookie", "cookie-signed"] }
dotenvy = "0.15.7"
env_logger = "0.10.0"
futures = "0.3.28"
handlebars = { version = "4.3.7", features = ["dir_source"] }
log = "0.4.19"
r_i18n = "1.0.1"
serde = { version = "1.0.180", features = ["derive"] }
serde_derive = "1.0.180"
serde_json = "1.0.104"
surrealdb = { version = "1.0.0-beta.9", features = ["kv-rocksdb"] }
tokio = { version = "1", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.4.3", features = ["fs"] }
