[package]
name = "avored-rust-cms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
dotenvy = "0.15.7"
env_logger = "0.10.0"
log = "0.4.19"
serde = { version = "1.0.180", features = ["derive"] }
serde_derive = "1.0.180"
serde_json = "1.0.104"
surrealdb = { version = "1.0.0-beta.9", features = ["kv-rocksdb"] }
tokio = { version = "1", features = ["full"] }
