name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag marks:$(date +%s)
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: github-action-auto-format
      # You may pin to the exact commit or the version.
      # uses: cloudposse/github-action-auto-format@970af4c15a720047204400fe5b5ae52fb2991e9b
      uses: cloudposse/github-action-auto-format@v0.12.0
      with:
        # GitHub username for writing new commits
        bot-name: "April John (cloudpossebot)" # optional, default is cloudpossebot
        # Email address associated with the GitHub user for writing new commits
        bot-email: "aprl@acab.dev" # optional
        # GitHub Token for use in `github_format.sh` and PR creation steps. This token must be granted `workflows` permissions.
        workflow-token: "{{ secrets.CI_TOKEN }}"
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: First interaction
      uses: actions/first-interaction@v1.1.1
      with:
        # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
        repo-token: "{{ secrets.CI_TOKEN }}"
