name: AvoRedCMS

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: avored rust cms build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@master
      - uses: Swatinem/rust-cache@v2.4.0
      - name: Build
        uses: rust-build/rust-build.action@v1.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}