on: pull_request

name: Rustfmt

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2.4.0
      - uses: mbrobbel/rustfmt-check@0.8.0
        with:
          token: ${{ secrets.CI_TOKEN }}
          mode: review