on: push

name: Rustfmt

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: mbrobbel/rustfmt-check@0.8.0
        with:
          token: ${{ secrets.CI_TOKEN }}